import * as React from 'react';
import { useReports } from '@/hooks/useReports';
import { Button } from '@/components/ui/Button';
import { Search, Filter, Trash2, Download, Archive, MoreHorizontal, FileText, Share2, Eye } from 'lucide-react';
import { Badge } from '@/components/ui/Badge';
import { cn } from '@/utils';
import type { ReportStatus, Report } from '@/types';

function getStatusBadge(status: ReportStatus) {
  switch (status) {
    case 'ready': return <Badge variant="success" dot>Ready</Badge>;
    case 'generating': return <Badge variant="primary" dot>Generating</Badge>;
    case 'failed': return <Badge variant="danger" dot>Failed</Badge>;
    case 'scheduled': return <Badge variant="warning" dot>Scheduled</Badge>;
    case 'archived': return <Badge variant="default" dot>Archived</Badge>;
    default: return <Badge variant="default" dot>{status}</Badge>;
  }
}

export function ReportLibrary() {
  const { 
    reports, isLoading, selectedReportIds, toggleReportSelection, 
    setSelectedReport, setIsPreviewOpen, setIsDetailsDrawerOpen,
    filters, setFilters
  } = useReports();

  // Simple filtering
  const filteredReports = reports.filter(r => {
    if (filters.search) {
      const q = filters.search.toLowerCase();
      if (!r.name.toLowerCase().includes(q) && !r.clientName.toLowerCase().includes(q)) return false;
    }
    return true;
  });

  const handleRowClick = (report: Report) => {
    setSelectedReport(report);
    setIsDetailsDrawerOpen(true);
  };

  const handlePreviewClick = (e: React.MouseEvent, report: Report) => {
    e.stopPropagation();
    setSelectedReport(report);
    setIsPreviewOpen(true);
  };

  return (
    <div className="section-card noPad flex flex-col relative">
      
      {/* Search & Filters */}
      <div className="p-4 border-b border-border flex flex-col sm:flex-row gap-4 justify-between bg-card rounded-t-xl">
        <div className="flex items-center gap-2">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <input 
              type="text"
              placeholder="Search reports... (Ctrl+K)"
              value={filters.search || ''}
              onChange={(e) => setFilters({ search: e.target.value })}
              className="h-9 w-full sm:w-64 pl-9 pr-3 text-sm rounded-lg border border-border bg-input focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all"
            />
          </div>
          <Button variant="outline" size="icon">
            <Filter className="h-4 w-4" />
          </Button>
        </div>

        {/* Bulk Actions - only visible when items selected */}
        {selectedReportIds.length > 0 && (
          <div className="flex items-center gap-2 animate-[fade-in_0.2s_ease-out]">
            <span className="text-body-sm text-muted-foreground mr-2">
              {selectedReportIds.length} selected
            </span>
            <Button variant="outline" size="sm" leftIcon={<Download className="w-3.5 h-3.5" />}>Download</Button>
            <Button variant="outline" size="sm" leftIcon={<Archive className="w-3.5 h-3.5" />}>Archive</Button>
            <Button variant="outline" size="sm" className="text-destructive border-destructive/30 hover:bg-destructive/5" leftIcon={<Trash2 className="w-3.5 h-3.5" />}>Delete</Button>
          </div>
        )}
      </div>

      {/* Table */}
      <div className="overflow-x-auto custom-scrollbar">
        <table className="w-full text-left border-collapse min-w-[800px]">
          <thead>
            <tr className="border-b border-border bg-secondary/50">
              <th className="px-4 py-3 w-10 text-center">
                <input type="checkbox" className="rounded border-border" disabled={reports.length === 0} />
              </th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Report Name</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Client</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Format</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Status</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Generated By</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold">Date</th>
              <th className="px-4 py-3 text-label text-muted-foreground font-semibold text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {isLoading ? (
              Array.from({ length: 4 }).map((_, i) => (
                <tr key={i} className="border-b border-border/50">
                  <td className="px-4 py-4"><div className="skeleton h-4 w-4 rounded" /></td>
                  <td className="px-4 py-4">
                    <div className="flex items-center gap-3">
                      <div className="skeleton h-8 w-8 rounded-lg" />
                      <div className="skeleton h-4 w-32 rounded" />
                    </div>
                  </td>
                  <td className="px-4 py-4"><div className="skeleton h-4 w-24 rounded" /></td>
                  <td className="px-4 py-4"><div className="skeleton h-5 w-12 rounded-full" /></td>
                  <td className="px-4 py-4"><div className="skeleton h-6 w-20 rounded-full" /></td>
                  <td className="px-4 py-4"><div className="skeleton h-4 w-24 rounded" /></td>
                  <td className="px-4 py-4"><div className="skeleton h-4 w-20 rounded" /></td>
                  <td className="px-4 py-4 text-right"><div className="skeleton h-8 w-8 rounded-lg ml-auto" /></td>
                </tr>
              ))
            ) : filteredReports.length === 0 ? (
              <tr>
                <td colSpan={8} className="px-6 py-16 text-center">
                  <div className="flex flex-col items-center justify-center">
                    <div className="h-12 w-12 rounded-full bg-secondary flex items-center justify-center mb-3">
                      <FileText className="h-6 w-6 text-muted-foreground" />
                    </div>
                    <h3 className="text-body font-semibold">No reports found</h3>
                    <p className="text-body-sm text-muted-foreground mt-1 mb-4">Try adjusting your filters or generate a new report.</p>
                  </div>
                </td>
              </tr>
            ) : (
              filteredReports.map((report) => {
                const isSelected = selectedReportIds.includes(report.id);
                return (
                  <tr 
                    key={report.id} 
                    onClick={() => handleRowClick(report)}
                    className={cn(
                      "border-b border-border/50 transition-colors cursor-pointer group",
                      isSelected ? "bg-primary/5 hover:bg-primary/10" : "hover:bg-secondary/50"
                    )}
                  >
                    <td className="px-4 py-4 text-center" onClick={(e) => e.stopPropagation()}>
                      <input 
                        type="checkbox" 
                        className="rounded border-border cursor-pointer accent-primary" 
                        checked={isSelected}
                        onChange={() => toggleReportSelection(report.id)}
                      />
                    </td>
                    <td className="px-4 py-4">
                      <div className="flex items-center gap-3">
                        <div className="h-8 w-8 rounded-lg bg-secondary flex items-center justify-center flex-shrink-0">
                          <FileText className="h-4 w-4 text-muted-foreground" />
                        </div>
                        <div>
                          <p className="text-body-sm font-semibold text-foreground group-hover:text-primary transition-colors">{report.name}</p>
                          <p className="text-caption text-muted-foreground">{report.type}</p>
                        </div>
                      </div>
                    </td>
                    <td className="px-4 py-4 text-body-sm font-medium">{report.clientName}</td>
                    <td className="px-4 py-4">
                      <Badge variant="default" className="text-[10px]">{report.format}</Badge>
                    </td>
                    <td className="px-4 py-4">{getStatusBadge(report.status)}</td>
                    <td className="px-4 py-4 text-sm text-muted-foreground">{report.generatedBy}</td>
                    <td className="px-4 py-4 text-sm text-muted-foreground">
                      {new Date(report.createdAt).toLocaleDateString()}
                    </td>
                    <td className="px-4 py-4 text-right">
                      <div className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <Button variant="ghost" size="icon" onClick={(e) => handlePreviewClick(e, report)} title="Preview">
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); }} title="Download">
                          <Download className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); }} title="Share">
                          <Share2 className="h-4 w-4" />
                        </Button>
                        <Button variant="ghost" size="icon" onClick={(e) => { e.stopPropagation(); }}>
                          <MoreHorizontal className="h-4 w-4" />
                        </Button>
                      </div>
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
