import * as React from 'react';
import { motion } from 'framer-motion';
import { Sparkles, Clock, AlertTriangle, ChevronRight } from 'lucide-react';
import { cn } from '@/utils';
import { Badge } from '@/components/ui/Badge';
import type { AISummary } from '../dashboard.types';
import { PLACEHOLDER_AI_SUMMARY } from '../dashboard.data';

// ============================================================
// AI Executive Summary Card
// ============================================================

interface ConfidenceRingProps {
  value: number; // 0–1
}

function ConfidenceRing({ value }: ConfidenceRingProps) {
  const radius = 20;
  const circ = 2 * Math.PI * radius;
  const filled = circ * value;

  return (
    <div className="flex flex-col items-center gap-1">
      <svg width="56" height="56" viewBox="0 0 56 56" aria-label={`Confidence: ${(value * 100).toFixed(0)}%`}>
        {/* Track */}
        <circle
          cx="28" cy="28" r={radius}
          fill="none"
          stroke="hsl(var(--border))"
          strokeWidth="4"
        />
        {/* Fill */}
        <circle
          cx="28" cy="28" r={radius}
          fill="none"
          stroke="hsl(var(--primary))"
          strokeWidth="4"
          strokeLinecap="round"
          strokeDasharray={`${filled} ${circ}`}
          transform="rotate(-90 28 28)"
          style={{ transition: 'stroke-dasharray 1s ease' }}
        />
        {/* Text */}
        <text
          x="28" y="28"
          textAnchor="middle"
          dominantBaseline="central"
          fontSize="11"
          fontWeight="700"
          fill="hsl(var(--foreground))"
        >
          {(value * 100).toFixed(0)}%
        </text>
      </svg>
      <p className="text-[10.5px] text-muted-foreground text-center">AI Confidence</p>
    </div>
  );
}

interface AISummaryCardProps {
  summary?: AISummary;
  className?: string;
}

export function AISummaryCard({ summary = PLACEHOLDER_AI_SUMMARY, className }: AISummaryCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, delay: 0.1 }}
      className={cn('section-card p-6', className)}
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-4 mb-4">
        <div className="flex items-start gap-3">
          <div className="flex h-9 w-9 flex-shrink-0 items-center justify-center rounded-lg bg-primary">
            <Sparkles className="h-4.5 w-4.5 text-white" strokeWidth={2} />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-[14.5px] font-semibold text-foreground leading-snug">
                AI Executive Summary
              </h2>
              <Badge variant="primary" size="sm">AI Generated</Badge>
            </div>
            <div className="flex items-center gap-1.5 mt-0.5">
              <Clock className="h-3 w-3 text-muted-foreground" />
              <p className="text-[11.5px] text-muted-foreground">
                Generated by Dirt2Dollar AI · {summary.generatedAt}
              </p>
            </div>
          </div>
        </div>

        {/* Confidence ring */}
        <div className="flex-shrink-0 hidden sm:block">
          <ConfidenceRing value={summary.confidence} />
        </div>
      </div>

      {/* Headline */}
      <p className="text-[14px] font-semibold text-foreground mb-2 leading-snug">
        {summary.headline}
      </p>

      {/* Body */}
      <p className="text-[13px] text-muted-foreground leading-relaxed mb-4">
        {summary.body}
      </p>

      {/* Flags */}
      {summary.flags.length > 0 && (
        <div className="flex flex-wrap gap-2 pt-3 border-t border-border">
          <span className="text-[11.5px] font-semibold text-muted-foreground flex items-center gap-1">
            <AlertTriangle className="h-3.5 w-3.5 text-warning" />
            Key Flags:
          </span>
          {summary.flags.map((flag, i) => (
            <Badge key={i} variant="warning" size="sm" dot>{flag}</Badge>
          ))}
        </div>
      )}
    </motion.div>
  );
}
